import { db } from "../lib/db";
import { catalogCategories, catalogItems } from "../lib/db/schema";

// Catálogo real da operação Kenkyo, importado da planilha "Posição de
// estoque" (Saipos). Categoria vem do "Grupo ingrediente" da planilha,
// com Peixes e Frutos do Mar + Bovinas/Suínas/Aves unificados em "Carnes
// e Pescados", e os ~50 itens sem grupo reclassificados manualmente. A
// unidade de medida não vem da planilha — foi inferida por categoria e
// por palavras-chave no nome; Produção Kenkyo e Secos e Mercearias foram
// os grupos mais "chutados", vale conferir esses na aba Catálogo.
//
// Aditivo e não-destrutivo: só insere item/categoria que ainda não
// existe (por nome); nunca sobrescreve uma edição que o Gestor já tenha
// feito pela aba Catálogo. Nunca fazer reseed destrutivo aqui.
const ITEMS: { name: string; category: string; unit: "kg" | "g" | "un" | "L" | "ml" | "cx" | "pct" }[] = [
  { name: "Abacaxi", category: "Hortifruti", unit: "kg" },
  { name: "Açucar Cristal", category: "Secos e Mercearias", unit: "kg" },
  { name: "Açucar Mascavo", category: "Secos e Mercearias", unit: "kg" },
  { name: "Açucar Refinado", category: "Secos e Mercearias", unit: "kg" },
  { name: "Adaptador Hashi", category: "Material de Uso e Consumo", unit: "pct" },
  { name: "Água com gás", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Agua Sanitaria", category: "Material de Limpeza", unit: "L" },
  { name: "Água sem gás", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Água Tônica", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Água Tônica Zero", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Alamos Cabernet Sauvignon", category: "Vinhos", unit: "un" },
  { name: "Alamos cabernet sauvignon - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Alamos Malbec, 2017 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Alamos Malbec, 2017 - Meia-Garrafa Único", category: "Vinhos", unit: "un" },
  { name: "Alamos Torrontés, 2022 - 750ml", category: "Vinhos", unit: "un" },
  { name: "Alamos Torrontés, 2022 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Alcool Liquido 70%", category: "Material de Limpeza", unit: "un" },
  { name: "Alecrim", category: "Frescos", unit: "kg" },
  { name: "Alga Kombu", category: "Secos e Mercearias", unit: "kg" },
  { name: "Alga Nori", category: "Secos e Mercearias", unit: "kg" },
  { name: "Alma Negra Misterio Blend - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Amendoas em Lascas", category: "Secos e Mercearias", unit: "kg" },
  { name: "Amêndoas tostadas", category: "Produção Kenkyo", unit: "kg" },
  { name: "Amido de Milho", category: "Secos e Mercearias", unit: "kg" },
  { name: "Amora Congelada", category: "Congelados", unit: "kg" },
  { name: "Anchova Defumada", category: "Carnes e Pescados", unit: "kg" },
  { name: "Anchova Natural", category: "Carnes e Pescados", unit: "kg" },
  { name: "Angostura Aromatic 200ml", category: "Destilados", unit: "un" },
  { name: "Angostura Orange", category: "Destilados", unit: "un" },
  { name: "Aperitivo Aperol 750 ML", category: "Destilados", unit: "un" },
  { name: "Aperitivo Campari", category: "Destilados", unit: "un" },
  { name: "Arroz Minamimai curto", category: "Secos e Mercearias", unit: "kg" },
  { name: "Atum", category: "Carnes e Pescados", unit: "kg" },
  { name: "Azeite de Olivia 5 Lts", category: "Secos e Mercearias", unit: "L" },
  { name: "Azeite Trufado", category: "Secos e Mercearias", unit: "L" },
  { name: "Azuma Dourado - Dose", category: "Destilados", unit: "un" },
  { name: "Azuma Dourado - Garrafa", category: "Destilados", unit: "un" },
  { name: "Baden Baden Cristal", category: "Cervejas", unit: "un" },
  { name: "Baden Baden Golden", category: "Cervejas", unit: "un" },
  { name: "Baden Baden Ipa", category: "Cervejas", unit: "un" },
  { name: "Baden Baden Witbier", category: "Cervejas", unit: "un" },
  { name: "Baly Energetico Tropical", category: "Bebidas", unit: "un" },
  { name: "Baran - Baran", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Base P/ Molho Tartaro", category: "Produção Kenkyo", unit: "L" },
  { name: "Batata", category: "Hortifruti", unit: "kg" },
  { name: "Batata Crinkle 2.5kg", category: "Frios e Laticinios", unit: "kg" },
  { name: "Bico p/ maçarico", category: "Utensilios", unit: "un" },
  { name: "Biscoito Negresco Triturado", category: "Secos e Mercearias", unit: "kg" },
  { name: "Blend Oleo de Gergelim", category: "Produção Kenkyo", unit: "kg" },
  { name: "Bobinas de Impressao", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Bom Ar Spray", category: "Material de Limpeza", unit: "un" },
  { name: "Borrifador 500 Ml", category: "Utensilios", unit: "un" },
  { name: "Brownie", category: "Sobremesas", unit: "un" },
  { name: "Cabeça de Polvo", category: "Carnes e Pescados", unit: "kg" },
  { name: "Cachaça Seleta", category: "Destilados", unit: "un" },
  { name: "Cafe Moido 500gr", category: "Secos e Mercearias", unit: "kg" },
  { name: "Caixa GG Personalizada", category: "Embalagens", unit: "pct" },
  { name: "Caixa G Personalizada", category: "Embalagens", unit: "pct" },
  { name: "Caixa M Personalizada", category: "Embalagens", unit: "pct" },
  { name: "Caixa PP Personalizada", category: "Embalagens", unit: "pct" },
  { name: "Calda Maracuja 5 Lts", category: "Produção Kenkyo", unit: "kg" },
  { name: "Calda Maracuja Trufada", category: "Produção Kenkyo", unit: "kg" },
  { name: "Calda Morango 5 Lts", category: "Produção Kenkyo", unit: "kg" },
  { name: "Camarao G", category: "Carnes e Pescados", unit: "kg" },
  { name: "Camarao M", category: "Carnes e Pescados", unit: "kg" },
  { name: "Campari", category: "Destilados", unit: "un" },
  { name: "Caneta Esferografica", category: "Material de Escritorio", unit: "un" },
  { name: "Canudo Flexivel 100Un", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Canudo Mexedor 100Un", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Carmen Insigne Aperitif Rosé - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Carmen Insigne Carmenere - 750ml", category: "Vinhos", unit: "un" },
  { name: "Carmen Insigne Carmenere - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Carmen Insigne Carmenere - Meia-Garrafa Único", category: "Vinhos", unit: "un" },
  { name: "Carmen Insigne Merlot (Sugestão da casa) - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Carmen Insigne Sauvignon Blanc, 2016 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Carmen insigne sauvignon blanc, 2016 - meia-garrafa único", category: "Vinhos", unit: "un" },
  { name: "Casa Del Maipo Merlot - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Casas Del Maipo Cabernet Sauvignon", category: "Vinhos", unit: "un" },
  { name: "Casas Del Maipo Cabernet Sauvignon - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Casas Del Maipo Carmenere - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "CASAS DEL MAIPO SAUVIGNON BLANC 750 ML", category: "Vinhos", unit: "un" },
  { name: "Catena Zapata Catena Chardonnay", category: "Vinhos", unit: "un" },
  { name: "Catena Zapata Catena Chardonnay - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Catena zapata catena malbec - 750ml", category: "Vinhos", unit: "un" },
  { name: "Catena Zapata Catena Malbec - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Catena Zapata Dv Catena Cabernet Malbec", category: "Vinhos", unit: "un" },
  { name: "Catena Zapata Dv Catena Cabernet Malbec, 2005 (Sugestão da casa) - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Cebola Branca", category: "Hortifruti", unit: "kg" },
  { name: "Cebola Roxa", category: "Hortifruti", unit: "kg" },
  { name: "Cebolinha", category: "Hortifruti", unit: "kg" },
  { name: "Cera Liquida Incolor", category: "Material de Limpeza", unit: "un" },
  { name: "Cerveja Heineken Zero", category: "Cervejas", unit: "un" },
  { name: "Chá gelado único", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Chamex Branco 500 Folhas", category: "Material de Escritorio", unit: "un" },
  { name: "Chandon Brut - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Chandon Brut Rosé - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Chimichurri", category: "Secos e Mercearias", unit: "kg" },
  { name: "Chips De Batata Doce", category: "Produção Kenkyo", unit: "kg" },
  { name: "Clips de Papel", category: "Material de Escritorio", unit: "un" },
  { name: "Coca cola", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Coca cola zero", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Coentro", category: "Hortifruti", unit: "kg" },
  { name: "Conde de barcelos rosé", category: "Vinhos", unit: "un" },
  { name: "Conde De Barcelos Rosé, 2013 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Condes de Barcelos, 2023 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Conserva dedo de moça", category: "Produção Kenkyo", unit: "kg" },
  { name: "Copo Descartavel 200 ml", category: "Material de Uso e Consumo", unit: "pct" },
  { name: "Corante Liquido Laranja", category: "Secos e Mercearias", unit: "kg" },
  { name: "Corona", category: "Cervejas", unit: "un" },
  { name: "Cream Cheese", category: "Frios e Laticinios", unit: "kg" },
  { name: "CreamCheese Polengui 1.5kg", category: "Frios e Laticinios", unit: "kg" },
  { name: "Creme de Leite 1 Lts", category: "Secos e Mercearias", unit: "L" },
  { name: "Crispy de Alho Poro Kg", category: "Produção Kenkyo", unit: "kg" },
  { name: "Crispy de Batata Doce", category: "Produção Kenkyo", unit: "kg" },
  { name: "Crispy de Couve Kg", category: "Produção Kenkyo", unit: "kg" },
  { name: "DCP 04 100 Un", category: "Embalagens", unit: "pct" },
  { name: "Desifentante Diversos 2 Lts", category: "Material de Limpeza", unit: "un" },
  { name: "Detergente Lava Louca 20 Lts", category: "Material de Limpeza", unit: "L" },
  { name: "Detergente Liquido Neutro", category: "Material de Limpeza", unit: "L" },
  { name: "DPC 0", category: "Embalagens", unit: "pct" },
  { name: "DPC 40 100 Un", category: "Embalagens", unit: "pct" },
  { name: "E.A Branco, 2009 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "EA cartuxa tinto, 2021 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Edamame Vagem", category: "Frescos", unit: "kg" },
  { name: "Emulsificante", category: "Secos e Mercearias", unit: "kg" },
  { name: "Escova de Lavar", category: "Material de Limpeza", unit: "un" },
  { name: "Espeto de Bambum P/ Drink", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Esponja Fibraco", category: "Material de Limpeza", unit: "un" },
  { name: "Esponja Limpeza Simples", category: "Material de Limpeza", unit: "un" },
  { name: "Espumante Aurora Brut", category: "Xaropes", unit: "L" },
  { name: "Espumante Aurora Rose", category: "Vinhos", unit: "un" },
  { name: "Essencia Concentrada", category: "Material de Limpeza", unit: "un" },
  { name: "Etiqueta de Validade 60x60 BOPP", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Farinha de Trigo 1kg", category: "Secos e Mercearias", unit: "kg" },
  { name: "Farinha Panko Alfa 1Kg", category: "Secos e Mercearias", unit: "kg" },
  { name: "Farinha Panko Romariz 1kg", category: "Secos e Mercearias", unit: "kg" },
  { name: "File de Atum", category: "Carnes e Pescados", unit: "kg" },
  { name: "File de Frango", category: "Carnes e Pescados", unit: "kg" },
  { name: "File de Tilapia", category: "Carnes e Pescados", unit: "kg" },
  { name: "Fina fatia de salmão", category: "Carnes e Pescados", unit: "kg" },
  { name: "Fita dupla face", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Fitzgerald único", category: "Cervejas", unit: "un" },
  { name: "Flanela Microfibra", category: "Material de Limpeza", unit: "un" },
  { name: "Flor de sal", category: "Secos e Mercearias", unit: "kg" },
  { name: "Frango", category: "Carnes e Pescados", unit: "kg" },
  { name: "Frasco Pet 30 ML", category: "Embalagens", unit: "pct" },
  { name: "Frasco Pet 60 Ml", category: "Embalagens", unit: "pct" },
  { name: "Frutas da estação", category: "Hortifruti", unit: "kg" },
  { name: "Frutas da estação em cubos", category: "Hortifruti", unit: "kg" },
  { name: "Frutas vermelhas", category: "Hortifruti", unit: "kg" },
  { name: "Frutos do mar", category: "Carnes e Pescados", unit: "kg" },
  { name: "Fumaça", category: "Produção Kenkyo", unit: "kg" },
  { name: "Fumaca Liquida", category: "Secos e Mercearias", unit: "kg" },
  { name: "Gas Butano P/ Macarico", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Gelo", category: "Material de Uso e Consumo", unit: "kg" },
  { name: "Gelo Cubos", category: "Bebidas", unit: "kg" },
  { name: "Gengibre em conserva", category: "Secos e Mercearias", unit: "kg" },
  { name: "Gengibre In natura", category: "Hortifruti", unit: "kg" },
  { name: "Gengibre Preparado 1kg", category: "Secos e Mercearias", unit: "kg" },
  { name: "Gergelim Torrado", category: "Produção Kenkyo", unit: "kg" },
  { name: "Gin Gordons", category: "Destilados", unit: "un" },
  { name: "Gin tropical", category: "Destilados", unit: "un" },
  { name: "Goiabada 300gr", category: "Secos e Mercearias", unit: "kg" },
  { name: "Gomasuri (Moedor de Gergelim)", category: "Utensilios", unit: "un" },
  { name: "Guaraná", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Guaraná zero", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Guardanapo Sache", category: "Material de Uso e Consumo", unit: "pct" },
  { name: "Guioza Suino", category: "Frios e Laticinios", unit: "kg" },
  { name: "H2OH Limoneto", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Hakushika - Dose", category: "Destilados", unit: "un" },
  { name: "Hakushika - Garrafa", category: "Destilados", unit: "un" },
  { name: "Hashi Preto Personalizado 50un", category: "Material de Uso e Consumo", unit: "pct" },
  { name: "Heineken", category: "Cervejas", unit: "un" },
  { name: "Heineken Zero", category: "Cervejas", unit: "un" },
  { name: "Hondashi", category: "Secos e Mercearias", unit: "kg" },
  { name: "Hortela", category: "Frescos", unit: "kg" },
  { name: "Inseticida Baygon", category: "Material de Limpeza", unit: "un" },
  { name: "Jackbull", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Kanikama", category: "Carnes e Pescados", unit: "kg" },
  { name: "Ketchup Sache", category: "Secos e Mercearias", unit: "kg" },
  { name: "Kiwi", category: "Hortifruti", unit: "kg" },
  { name: "Laranja Bahia", category: "Hortifruti", unit: "kg" },
  { name: "Laranja Desidratada", category: "Produção Kenkyo", unit: "kg" },
  { name: "Laranja Saco", category: "Hortifruti", unit: "kg" },
  { name: "Leite Condensado 5kg", category: "Secos e Mercearias", unit: "L" },
  { name: "Leite Integral", category: "Secos e Mercearias", unit: "L" },
  { name: "Lemon Pepper", category: "Secos e Mercearias", unit: "kg" },
  { name: "Le Petit Maynne Pinot Noir, 2012 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Licor 43", category: "Destilados", unit: "un" },
  { name: "Licor de café", category: "Destilados", unit: "un" },
  { name: "Limao Siciliano", category: "Frescos", unit: "kg" },
  { name: "Limao Taiti", category: "Frescos", unit: "kg" },
  { name: "Love Pink Rosé, 2016 - Meia-Garrafa Único", category: "Vinhos", unit: "un" },
  { name: "Love Red, 2019 (Sugestão da casa) - Meia-Garrafa Único", category: "Vinhos", unit: "un" },
  { name: "Luva Descartável G", category: "Material de Uso e Consumo", unit: "pct" },
  { name: "Luva Descartável M", category: "Material de Uso e Consumo", unit: "pct" },
  { name: "Luva Latex Para Limpeza", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Macarrao Nissin Yakisoba", category: "Secos e Mercearias", unit: "kg" },
  { name: "Maca Verde", category: "Hortifruti", unit: "kg" },
  { name: "Mandolin Fatiador", category: "Utensilios", unit: "un" },
  { name: "Maracujá", category: "Hortifruti", unit: "kg" },
  { name: "Maracuja Congelado", category: "Polpas e sucos", unit: "kg" },
  { name: "Margarina 1kg", category: "Frios e Laticinios", unit: "kg" },
  { name: "Martini Rosso", category: "Destilados", unit: "un" },
  { name: "Massa de Harumaki", category: "Frios e Laticinios", unit: "kg" },
  { name: "Mirtilo Congelado", category: "Congelados", unit: "kg" },
  { name: "Mirtilo In Natura", category: "Frescos", unit: "kg" },
  { name: "Mistura P/ Tempura", category: "Secos e Mercearias", unit: "kg" },
  { name: "Mix de Legumes P/ Yakisoba", category: "Produção Kenkyo", unit: "kg" },
  { name: "Molho Cítrico", category: "Molhos e Caldas", unit: "L" },
  { name: "Molho gorgonzola", category: "Molhos e Caldas", unit: "L" },
  { name: "Molho Ponzu", category: "Molhos e Caldas", unit: "L" },
  { name: "Molho Shoyu Kikkoman 20 Lts", category: "Molhos e Caldas", unit: "L" },
  { name: "Molho Su Kenkyo 20 Lts", category: "Molhos e Caldas", unit: "L" },
  { name: "Molho Sweet Chilli 5kg", category: "Molhos e Caldas", unit: "L" },
  { name: "Molho Teryaki Kenkyo 20 Lts", category: "Produção Kenkyo", unit: "L" },
  { name: "Molho Yakisoba Kenkyo 5 Lts", category: "Produção Kenkyo", unit: "L" },
  { name: "Monte Velho - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Morango Congelado", category: "Congelados", unit: "kg" },
  { name: "Morango In Natura BDJ", category: "Frescos", unit: "kg" },
  { name: "Mostarda Amarela 1 Lts", category: "Secos e Mercearias", unit: "kg" },
  { name: "Mussarela Barra", category: "Frios e Laticinios", unit: "kg" },
  { name: "Oleo de Algodao 15.8 Lts", category: "Secos e Mercearias", unit: "kg" },
  { name: "Oleo de Gergelim Hong Kong 1 Lts", category: "Secos e Mercearias", unit: "kg" },
  { name: "Oleo de Soja 900 ml", category: "Secos e Mercearias", unit: "kg" },
  { name: "ORIGEM CHARDONNAY, 2021 - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Ovas Tobiko Black", category: "Carnes e Pescados", unit: "kg" },
  { name: "Ovos Cartela 30 Un", category: "Secos e Mercearias", unit: "kg" },
  { name: "Pano de Chao", category: "Material de Limpeza", unit: "un" },
  { name: "Papel Aluminio", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Papel Higienico Clientes (Elegans)", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Papel Higienico Func (Rolao)", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Papel Manteiga Perso Kenkyo", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Papel Toalha Interfolha", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Papel Toalha Rolo Simples", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Pasta de Misso", category: "Secos e Mercearias", unit: "kg" },
  { name: "Patê de salmão", category: "Carnes e Pescados", unit: "kg" },
  { name: "Pele de salmão", category: "Carnes e Pescados", unit: "kg" },
  { name: "Pele de salmão grelhada", category: "Produção Kenkyo", unit: "kg" },
  { name: "Pepino", category: "Hortifruti", unit: "kg" },
  { name: "Pepsi 350ml", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Pepsi black", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Perfex Azul", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Peroxy 5 Lts", category: "Material de Limpeza", unit: "un" },
  { name: "Pessego em Conserva", category: "Secos e Mercearias", unit: "kg" },
  { name: "Petit Gateu Chocolate", category: "Sobremesas", unit: "un" },
  { name: "Pimenta Calabresa Kg", category: "Secos e Mercearias", unit: "kg" },
  { name: "Pimenta Sriracha", category: "Secos e Mercearias", unit: "kg" },
  { name: "Pimenta Tabasco Original", category: "Secos e Mercearias", unit: "kg" },
  { name: "Plastico Filme", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Polpa Frutas Vermelhas", category: "Polpas e sucos", unit: "kg" },
  { name: "Polpa Maracuja", category: "Polpas e sucos", unit: "kg" },
  { name: "Polpa Morango", category: "Polpas e sucos", unit: "kg" },
  { name: "Porcao File Mignon 100Gr", category: "Produção Kenkyo", unit: "kg" },
  { name: "Porcao Frango 100Gr", category: "Produção Kenkyo", unit: "kg" },
  { name: "Porcao Mista File Mignon e Frango 100gr", category: "Produção Kenkyo", unit: "kg" },
  { name: "Pote Misso", category: "Embalagens", unit: "pct" },
  { name: "Queijo Gorgonzola", category: "Frios e Laticinios", unit: "kg" },
  { name: "Red Bull Tradicional", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Reducao Vinho Kenkyo 5 Lts", category: "Molhos e Caldas", unit: "L" },
  { name: "Requeijao Bisnaga 1.8Kg", category: "Frios e Laticinios", unit: "kg" },
  { name: "Rodo", category: "Material de Limpeza", unit: "un" },
  { name: "Sabonete Liquido Antisseptico", category: "Material de Limpeza", unit: "un" },
  { name: "Sabonete Liquido Perfumado", category: "Material de Limpeza", unit: "un" },
  { name: "Saco de Lixo 100 Lts Reforcado", category: "Material de Limpeza", unit: "un" },
  { name: "Saco de Lixo 30 Lts", category: "Material de Limpeza", unit: "un" },
  { name: "Saco de Lixo 50 Lts", category: "Material de Limpeza", unit: "un" },
  { name: "Saco de Lixo 60 Lts Reforcado", category: "Material de Limpeza", unit: "un" },
  { name: "Sacola Pers P/ Delivery G", category: "Embalagens", unit: "pct" },
  { name: "Sacola Pers P/ Delivery P", category: "Embalagens", unit: "pct" },
  { name: "Saco Plástico 10x15x0,06 Liso", category: "Embalagens", unit: "pct" },
  { name: "Saco Plastico 15X25", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Saco Plástico 15x30x0,012 Liso", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Saco Plastico 25X35", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Saco Plástico 30x40x0,06 Liso", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Saco Plastico Bobina 05kg", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Saco Plastico Bobina 10kg", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Saco Zip N2", category: "Embalagens", unit: "pct" },
  { name: "Sal", category: "Secos e Mercearias", unit: "kg" },
  { name: "Salmao Inteiro 12/14", category: "Carnes e Pescados", unit: "kg" },
  { name: "Sal Rosa do Himalaia", category: "Secos e Mercearias", unit: "kg" },
  { name: "Salsa Crespa", category: "Hortifruti", unit: "kg" },
  { name: "Santa Dica Catharina Sour 355ml", category: "Cervejas", unit: "un" },
  { name: "Santa Dica IPA 600ml", category: "Cervejas", unit: "un" },
  { name: "Saque Mirim", category: "Secos e Mercearias", unit: "kg" },
  { name: "Schweppes", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Schweppes 1,5L", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Secante Lava Louca 20 Lt", category: "Material de Limpeza", unit: "un" },
  { name: "Shimeji Preto", category: "Frescos", unit: "kg" },
  { name: "Soda Limonada", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Sorvete", category: "Sobremesas", unit: "un" },
  { name: "Soverte Creme 10 Lts", category: "Sobremesas", unit: "un" },
  { name: "Sprite", category: "Refrigerantes e Aguas", unit: "un" },
  { name: "Stella Artois Pure Gold", category: "Cervejas", unit: "un" },
  { name: "Suco de laranja", category: "Polpas e sucos", unit: "kg" },
  { name: "Sunomono 1kg", category: "Produção Kenkyo", unit: "kg" },
  { name: "Tampa Plast 24 MM C/ Lacre", category: "Embalagens", unit: "pct" },
  { name: "Tempero Kenkyo (Alho Poró)", category: "Produção Kenkyo", unit: "g" },
  { name: "Tempero Padrao Kenkyo 1kg", category: "Produção Kenkyo", unit: "g" },
  { name: "Tempero P/ GravLax", category: "Produção Kenkyo", unit: "g" },
  { name: "Tempero Shio Kosho 1KG", category: "Produção Kenkyo", unit: "g" },
  { name: "Tempero Sirio", category: "Secos e Mercearias", unit: "g" },
  { name: "Tentaculo de Polvo", category: "Carnes e Pescados", unit: "kg" },
  { name: "Togarashi", category: "Secos e Mercearias", unit: "kg" },
  { name: "Touca Descartavel", category: "Material de Uso e Consumo", unit: "un" },
  { name: "Uxmal Chardonnay - 750ml Único", category: "Vinhos", unit: "un" },
  { name: "Vassoura", category: "Material de Limpeza", unit: "un" },
  { name: "Vermute rosso", category: "Destilados", unit: "un" },
  { name: "Vinagre de Arroz Castelo 20 Lts", category: "Secos e Mercearias", unit: "L" },
  { name: "Vinho Alamos Malbec", category: "Vinhos", unit: "un" },
  { name: "Vinho Branco", category: "Secos e Mercearias", unit: "kg" },
  { name: "Vinho Carmen Insigne Aperitif Rosé", category: "Vinhos", unit: "un" },
  { name: "Vinho Casas Del Maipo Carmenere", category: "Vinhos", unit: "un" },
  { name: "Vinho EA Cartuxa Tinto", category: "Vinhos", unit: "un" },
  { name: "Vinho Love Pink Rosé", category: "Vinhos", unit: "un" },
  { name: "Vinho Love Red", category: "Vinhos", unit: "un" },
  { name: "Vinho Origem Chardonnay", category: "Vinhos", unit: "un" },
  { name: "Vinho Tinto", category: "Secos e Mercearias", unit: "kg" },
  { name: "Vinho Uxmal Chardonnay", category: "Vinhos", unit: "un" },
  { name: "VixClor 5 Lts", category: "Material de Limpeza", unit: "un" },
  { name: "VixFort 5 Lts", category: "Material de Limpeza", unit: "un" },
  { name: "Vodka Smirnoff", category: "Destilados", unit: "un" },
  { name: "Wasabi em Po 1kg", category: "Secos e Mercearias", unit: "kg" },
  { name: "Wasabi Sache 500un", category: "Secos e Mercearias", unit: "kg" },
  { name: "Whisky Ballantines Finest", category: "Destilados", unit: "un" },
  { name: "Whisky Jack Daniels", category: "Destilados", unit: "un" },
  { name: "XAROPE MONIN AMORA", category: "Xaropes", unit: "L" },
  { name: "XAROPE MONIN CRANBERRY", category: "Xaropes", unit: "L" },
  { name: "XAROPE MONIN DE MAÇÃ VERDE", category: "Xaropes", unit: "L" },
  { name: "XAROPE MONIN GRENADINE", category: "Xaropes", unit: "L" },
  { name: "XAROPE MONIN LIMÃO SICILIANO", category: "Xaropes", unit: "L" },
  { name: "XAROPE MONIN MARACUJÁ", category: "Xaropes", unit: "L" },
  { name: "XAROPE MONIN MORANGO", category: "Xaropes", unit: "L" },
];

async function main() {
  const categoryNames = [...new Set(ITEMS.map((i) => i.category))];

  const existingCategories = await db.select().from(catalogCategories);
  const categoryIdByName = new Map(existingCategories.map((c) => [c.name, c.id]));

  for (const name of categoryNames) {
    if (categoryIdByName.has(name)) continue;
    const [created] = await db.insert(catalogCategories).values({ name }).returning({ id: catalogCategories.id });
    categoryIdByName.set(name, created.id);
    console.log(`Categoria criada: ${name}`);
  }

  const existingItems = await db.select({ name: catalogItems.name }).from(catalogItems);
  const existingNames = new Set(existingItems.map((i) => i.name));

  const toInsert = ITEMS.filter((i) => !existingNames.has(i.name)).map((i) => ({
    name: i.name,
    categoryId: categoryIdByName.get(i.category) ?? null,
    unitMeasure: i.unit,
  }));

  if (toInsert.length === 0) {
    console.log("Nenhum produto novo para inserir.");
  } else {
    await db.insert(catalogItems).values(toInsert);
    console.log(`${toInsert.length} produto(s) inserido(s).`);
  }

  console.log("Concluído.");
}

main();
